### ISSUE TITLE
Mapbox visual not showing in embedded Power BI reports

### ISSUE THREAD

**Issue by mBoegebjerg** [starschema/mapboxgl-powerbi#19]
Hi
As of today, our map visualizations have stopped working in our embedded environment. We have tried with version 1.5 and 1.6. The previous known problem with LastPass in Google Chrome is not causing the issue. We get a 403 HTTP error code, related to the authorization. 

I see on other forums that many are experiencing the same issue. I hope you can fix it, as we, as well as others, very much depend on your good service. 

Thanks.

**Comment by mate-turi** [comment]
Based on the last comment, i'm closing the issue.
