### ISSUE TITLE
[BUG] - Null instead of 0 on choropleth maps

### ISSUE THREAD

**Issue by mate-turi** [starschema/mapboxgl-powerbi#34]
**Describe the bug**
When a calculation results 0, for example 0/35, on choropleth maps, the result is null instead of 0.
![image](https://user-images.githubusercontent.com/9896505/186876242-86520f14-fa72-4291-af06-b02e96180e4d.png)
As the image shows, the built in visual (for example table) shows 0 for the measure, but the Mapbox Custom Visual tooltip shows null, instead of 0.

In this case, when I'm using the measure as color input, the legend does not appear, however it should be with one row, where red means 0.
![image](https://user-images.githubusercontent.com/9896505/186876787-62118eb2-6363-4ff4-a26c-f9cdd9e0dc20.png)

The calculation behind the Test Measure v2 is 0/35.

**To Reproduce**
1. Create a new measure with a simple content like 0/35
2. Create a choropleth and use the measure as color and tooltip, location should be states for example.
3. Hover any of the states, and null appears on the tooltip instead of 0.

**Expected behavior**
Shown value should be 0 instead of null.

**Comment by Saadyounus** [comment]
Still facing this issue.
Blank, 0 values showing as null. Any possible solution, workaround.
