### ISSUE TITLE
Tileset only showing up when super zoomed in on PowerBI mapbox choropleth map

### ISSUE THREAD

**Issue by aliciaoberholzer** [starschema/mapboxgl-powerbi#69]
I uploaded a GeoJSON of Kenya counties to mapbox and it automatically set the zoom range to between 7 and 13, so I can't see all the polygons in a single view. I can only see them when I'm zoomed in super close. Then, when using the tileset to try and make a choropleth mapbox map in PowerBI, I can only see my choropleth map when I zoom in to 7 or higher (see attached screenshots below, the second one shows how far zoomed in I need to be for the tileset to appear in my powerbi mapbox map and the second shows how the polygons aren't visible at the zoom level that I'd like them to be visible at). Is there any way I can configure my tileset to be able to see my entire choropleth map in the view?

<img width="1381" alt="tilesetview" src="https://github.com/starschema/mapboxgl-powerbi/assets/92735518/a68121b2-6822-44c1-91de-1e11350bffef">

<img width="694" alt="zoomed_in" src="https://github.com/starschema/mapboxgl-powerbi/assets/92735518/4c523797-bccd-4a94-94e3-bfe56d64cb72">

<img width="689" alt="Zoomedout" src="https://github.com/starschema/mapboxgl-powerbi/assets/92735518/e9eac91c-af22-492f-be3f-4f723176642d">

**Comment by mBoegebjerg** [comment]
This is related to how you have uploaded your Tileset to mapbox studio. You might need to upload it through the API and specify the zoom level. We had the same issues.

**Comment by aliciaoberholzer** [comment]
@mBoegebjerg yep - I ended up using the web tile service...also note that if you use a zoom-level above 10, you will be charged (I didn't see this immediately in the documentation and received a surprise invoice).
